baseURL = "https://www.yongyu.info"
languageCode = "en-us"
title = "Yongyu Xie"
theme = "barks"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:yxie405@gatech.edu"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/unaxiee"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=<your_user_id>"
        weight = 3
